#!/bin/bash

# script to stop service by name

CENTRALD_FILE=/etc/rts2/centrald
DEVICE_CONFIG=/etc/rts2/devices
SERVICE_CONFIG=/etc/rts2/services

if [ "x$1" == "x" ]; then
	echo "stopping everything"
	name="all"
else
	name=$1
fi

if [ "x$name" == "xcentrald" -o "x$name" == "xall" ]; then
	stopped=1
	while read centrald centrald_port centrald_options; do
		if [ "x${centrald_port}" == "x" ]; then
			centrald_port=617
		fi
		echo -n "stopping centrald on port $centrald_port .. "
		kill `cat /var/run/rts2_centrald_$centrald_port` 2>>/dev/null
		stopped=$?
		[ $stopped == 0 ] && echo "killed" || echo "failed"
		if [ $stopped != 0 -a "x$name" != "xall" ]; then
			exit 1
		fi
	done < <(grep '^centrald' $CENTRALD_FILE)
	if [ "x$name" != "xall" ]; then
		exit $stopped
	fi
fi

if [ "x$name" == "xall" ]; then
	while read device type device_name options; do
		echo -n "stopping device $device_name .. "
		kill `cat /var/run/rts2_$device_name` 2>>/dev/null
		stopped=$?
		[ $stopped == 0 ] && echo "killed" || echo "failed"
	done < <(cat $DEVICE_CONFIG | sed -e 's/#.*$//' | egrep -v '^\s*$')

	while read service service_name options; do
		echo -n "stopping service $service_name .. "
		kill `cat /var/run/rts2_$service_name` 2>>/dev/null
		stopped=$?
		[ $stopped == 0 ] && echo "killed" || echo "failed"
	done < <(cat $SERVICE_CONFIG | sed -e 's/#.*$//' | egrep -v '^\s*$')
else
	echo -n "stopping $name .. "
	kill `cat /var/run/rts2_$name`
	stopped=$?
	[ $stopped == 0 ] && echo "killed" || echo "failed"
fi

[ "x$name" != "xall" ] && exit $stopped || exit 0
