#!/bin/bash
case "$1" in
        [1,5])
                echo "E 0"
                ;;
        [2,4])
                echo "E 1 E 1 E 1"
                ;;
        3)
                echo "E 5"
                ;;
        *)
                echo "E 0"
        
esac
